### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/react-state-readme#1]
The link at "Props in getInitialState Is an Anti-Pattern" in the Resources section points to an unrelated section of React documentation.

It appears `getInitalState` is used  with React pre-ES6: https://reactjs.org/docs/react-without-es6.html#setting-the-initial-state
Since this seems to be outdated information that a student would have to try pretty hard to find, I'm wondering if we even need to mention it at all.

#staff

**Comment by maxwellbenton** [comment]
Hey @AspenJames,

I agree 100%. Removed!
